version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: verceldb
      POSTGRES_USER: default
      POSTGRES_PASSWORD: LDeE1ZiX6aCG
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: gunicorn stylesync.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
